# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Fatto a Mano
email: fatto-a-mano@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio website with handmade fabric products.
  You will find useful information about our team, our projects and the
  materials we use.
  Please contact us for more info.
author: Michi
keyword: handmade fabric
baseurl: "/fatto-a-mano" # the subpath of your site, e.g. /blog
url: "https://michele-alberti.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fatto-a-mano
github_username: fatto-a-mano

sections:
  nav:
    name: navigazione
    enabled: true
  hero:
    name: hero
    heading: fatto a mano
    enabled: true
  services:
    name: prodotti
    heading: prodotti
    enabled: true
  portfolio:
    name: portfolio
    heading: portfolio
    enabled: true
  about:
    name: chi siamo
    heading: chi siamo
    enabled: true
  team:
    name: team
    heading: la squadra
    enabled: true
  clients:
    name: clienti
    heading: null
    enabled: false
  contact:
    name: contattaci
    heading: contattaci
    enabled: true
  portfolio-modals:
    name: prodotto
    heading: null
    enabled: true
  footer:
    name: piè di pagina
    enabled: true

# Build settings
markdown: kramdown
#theme: agency-jekyll-theme #The "agency-jekyll-theme" is not supported by GitHub Pages.
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
